### ISSUE TITLE
This is not buildable

### ISSUE THREAD

**Issue by phoe** [wadehennessey/rtgc#1]
```
$  make
gcc -o a -Og -g a.c -L/home/phoe/lisp/rtgc -lrtgc -lpthread -lc -lm -ldl
/usr/bin/ld: cannot find -lrtgc
collect2: error: ld returned 1 exit status
```

How should I build this?

**Comment by wadehennessey** [comment]
Are you trying to build rtgc? You need to set the -L argument to the
correct rtgc directory. You also have to add it to your LD_LIBRARY_PATH if
you want ./a or any thing else linked against rtgc to run.

Are you trying to use rtgc for something? Your just building a simple test
program that exercises rtgc. -wade

**Comment by wadehennessey** [comment]
Try doing "make lib" first (or "make opt-lib" if you care about speed and not debugging).
Then "make a" should compile.

You will need to set your LD_LIBRARY_PATH correctly so ./a (or any binary linked against librtgc.so) can find the library at runtime. You'll have to install the library in someplace like /usr/lib64 if you want to avoid dealing with LD_LIBRARY_PATH. -wade

**Comment by wadehennessey** [comment]
On second thought, I realized you probably did set -L correctly, but you
didn't build librtgc.so first. Try:

make lib
or
make opt-lib (if you want it optimized and don't care about debugging info).

You still need to set LD_LIBRARY_PATH if you want programs to find
librtgc.so (unless you install that in a standard shared library
directory). -wade

**Comment by wadehennessey** [comment]
I fixed the Makefile so that the default make target will automatically create librtgc.so for you so you won't have this compile problem. You'll still need to setup LD_LIBRARY_PATH as mentioned above to run executables that link with librtgc.so.

Are you trying to use rtgc for a specific application? The "a" program you are trying to compile/run is just a simple test program for rtgc. See https://github.com/wadehennessey/wcl for an implementaion of Common Lisp that now uses rtgc if you want to see a real application. -wade

**Comment by phoe** [comment]
The makefile constantly points to `/home/wade/rtgc` which is not a valid path anywhere outside your system.

**Comment by wadehennessey** [comment]
I've changed /home/wade/rtgc to ./ and now the Makefile should work without changes. -wade

**Comment by phoe** [comment]
Thanks - I'm able to build this now. Closing.
